version: "3.8"
services:
  api:
    volumes:
      - ./:/usr/src/app:cached
      - /usr/src/app/node_modules
    command: npm run dev

  email-worker:
    volumes:
      - ./:/usr/src/app:cached
      - /usr/src/app/node_modules
    command: ["node", "src/worker/emailWorker.js"]
