version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: whms
      POSTGRES_PASSWORD: whmspass
      POSTGRES_DB: whms_dev
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
