export const dashboardStats = {
  totalClients: 2847,
  activeServers: 156,
  totalDomains: 4231,
  monthlyRevenue: 89420,
  ticketsOpen: 23,
  serverUptime: 99.97,
}

export const recentActivity = [
  { id: 1, type: "client", action: "New client registered", user: "john@example.com", time: "2 min ago" },
  { id: 2, type: "domain", action: "Domain transferred", user: "sarah@domain.io", time: "5 min ago" },
  { id: 3, type: "backup", action: "Backup completed", user: "System", time: "12 min ago" },
  { id: 4, type: "security", action: "Failed login attempt blocked", user: "unknown", time: "15 min ago" },
  { id: 5, type: "automation", action: "Cron job executed", user: "System", time: "20 min ago" },
]

export const clients = [
  {
    id: 1,
    name: "Acme Corp",
    email: "admin@acme.com",
    status: "active",
    domains: 12,
    created: "2024-01-15",
    revenue: 450,
  },
  {
    id: 2,
    name: "TechStart Inc",
    email: "info@techstart.io",
    status: "active",
    domains: 5,
    created: "2024-02-20",
    revenue: 180,
  },
  {
    id: 3,
    name: "GlobalWeb Ltd",
    email: "contact@globalweb.com",
    status: "suspended",
    domains: 8,
    created: "2023-11-10",
    revenue: 320,
  },
  {
    id: 4,
    name: "Digital Dreams",
    email: "hello@digitaldreams.co",
    status: "active",
    domains: 3,
    created: "2024-03-05",
    revenue: 90,
  },
  {
    id: 5,
    name: "WebMasters Pro",
    email: "support@webmasters.pro",
    status: "active",
    domains: 25,
    created: "2023-08-22",
    revenue: 890,
  },
  {
    id: 6,
    name: "CloudNine Solutions",
    email: "ops@cloudnine.dev",
    status: "pending",
    domains: 0,
    created: "2024-06-01",
    revenue: 0,
  },
]

export const domains = [
  {
    id: 1,
    domain: "example.com",
    client: "Acme Corp",
    status: "active",
    expires: "2025-01-15",
    ssl: true,
    dns: "Cloudflare",
  },
  {
    id: 2,
    domain: "techstart.io",
    client: "TechStart Inc",
    status: "active",
    expires: "2025-03-20",
    ssl: true,
    dns: "Internal",
  },
  {
    id: 3,
    domain: "globalweb.net",
    client: "GlobalWeb Ltd",
    status: "expiring",
    expires: "2024-07-10",
    ssl: true,
    dns: "Route53",
  },
  {
    id: 4,
    domain: "dreamsite.co",
    client: "Digital Dreams",
    status: "active",
    expires: "2025-06-05",
    ssl: false,
    dns: "Internal",
  },
  {
    id: 5,
    domain: "webmasters.pro",
    client: "WebMasters Pro",
    status: "active",
    expires: "2025-08-22",
    ssl: true,
    dns: "Cloudflare",
  },
]

export const backups = [
  {
    id: 1,
    name: "Full Server Backup",
    type: "full",
    size: "45.2 GB",
    status: "completed",
    date: "2024-06-01 03:00",
    retention: "30 days",
  },
  {
    id: 2,
    name: "Database Backup",
    type: "database",
    size: "2.1 GB",
    status: "completed",
    date: "2024-06-01 04:00",
    retention: "7 days",
  },
  {
    id: 3,
    name: "Files Backup",
    type: "files",
    size: "12.8 GB",
    status: "in-progress",
    date: "2024-06-01 05:00",
    retention: "14 days",
  },
  {
    id: 4,
    name: "Config Backup",
    type: "config",
    size: "128 MB",
    status: "scheduled",
    date: "2024-06-02 03:00",
    retention: "90 days",
  },
]

export const automations = [
  {
    id: 1,
    name: "Daily Backup",
    trigger: "cron",
    schedule: "0 3 * * *",
    status: "active",
    lastRun: "2024-06-01 03:00",
    nextRun: "2024-06-02 03:00",
  },
  {
    id: 2,
    name: "SSL Renewal Check",
    trigger: "cron",
    schedule: "0 0 * * 0",
    status: "active",
    lastRun: "2024-05-26 00:00",
    nextRun: "2024-06-02 00:00",
  },
  {
    id: 3,
    name: "Welcome Email",
    trigger: "event",
    schedule: "on_client_create",
    status: "active",
    lastRun: "2024-06-01 10:30",
    nextRun: "-",
  },
  {
    id: 4,
    name: "Invoice Generation",
    trigger: "cron",
    schedule: "0 0 1 * *",
    status: "paused",
    lastRun: "2024-05-01 00:00",
    nextRun: "-",
  },
]

export const plugins = [
  {
    id: 1,
    name: "Cloudflare Integration",
    version: "2.1.0",
    status: "active",
    author: "WHMS Team",
    installed: "2024-01-15",
  },
  { id: 2, name: "Stripe Payments", version: "3.0.2", status: "active", author: "WHMS Team", installed: "2024-02-20" },
  {
    id: 3,
    name: "WHM/cPanel Connector",
    version: "1.5.1",
    status: "active",
    author: "Third Party",
    installed: "2024-03-10",
  },
  {
    id: 4,
    name: "Email Marketing",
    version: "1.2.0",
    status: "inactive",
    author: "Third Party",
    installed: "2024-04-05",
  },
  {
    id: 5,
    name: "Support Ticketing",
    version: "2.0.0",
    status: "active",
    author: "WHMS Team",
    installed: "2024-01-01",
  },
]

export const sessions = [
  {
    id: 1,
    user: "admin@whms.io",
    ip: "192.168.1.100",
    location: "New York, US",
    device: "Chrome / Windows",
    started: "2024-06-01 09:00",
    lastActivity: "2 min ago",
    current: true,
  },
  {
    id: 2,
    user: "support@whms.io",
    ip: "192.168.1.101",
    location: "London, UK",
    device: "Firefox / macOS",
    started: "2024-06-01 08:30",
    lastActivity: "15 min ago",
    current: false,
  },
  {
    id: 3,
    user: "admin@whms.io",
    ip: "10.0.0.50",
    location: "San Francisco, US",
    device: "Safari / iOS",
    started: "2024-05-31 22:00",
    lastActivity: "8 hours ago",
    current: false,
  },
]

export const apiKeys = [
  {
    id: 1,
    name: "Production API",
    key: "whms_prod_****8x2k",
    permissions: ["read", "write"],
    created: "2024-01-15",
    lastUsed: "2 min ago",
    status: "active",
  },
  {
    id: 2,
    name: "Backup Service",
    key: "whms_bkup_****3f9m",
    permissions: ["read"],
    created: "2024-02-20",
    lastUsed: "1 hour ago",
    status: "active",
  },
  {
    id: 3,
    name: "Legacy Integration",
    key: "whms_leg_****7h4n",
    permissions: ["read", "write", "admin"],
    created: "2023-06-10",
    lastUsed: "30 days ago",
    status: "revoked",
  },
]

export const roles = [
  { id: 1, name: "Super Admin", users: 2, permissions: 45, description: "Full system access" },
  {
    id: 2,
    name: "Administrator",
    users: 5,
    permissions: 38,
    description: "Administrative access without system settings",
  },
  { id: 3, name: "Support Agent", users: 12, permissions: 15, description: "Client support and ticket management" },
  { id: 4, name: "Billing", users: 3, permissions: 12, description: "Invoice and payment management" },
  { id: 5, name: "Read Only", users: 8, permissions: 5, description: "View-only access to dashboard" },
]

export const webhooks = [
  {
    id: 1,
    name: "Slack Notifications",
    url: "https://hooks.slack.com/***",
    events: ["client.created", "ticket.opened"],
    status: "active",
    lastTriggered: "5 min ago",
  },
  {
    id: 2,
    name: "CRM Sync",
    url: "https://api.crm.com/webhook/***",
    events: ["client.created", "client.updated"],
    status: "active",
    lastTriggered: "1 hour ago",
  },
  {
    id: 3,
    name: "Analytics",
    url: "https://analytics.io/ingest/***",
    events: ["order.completed"],
    status: "failing",
    lastTriggered: "2 hours ago",
  },
]

export const securityLogs = [
  {
    id: 1,
    event: "Login Success",
    user: "admin@whms.io",
    ip: "192.168.1.100",
    time: "2024-06-01 09:00",
    severity: "info",
  },
  {
    id: 2,
    event: "Failed Login Attempt",
    user: "unknown",
    ip: "45.33.32.156",
    time: "2024-06-01 08:45",
    severity: "warning",
  },
  {
    id: 3,
    event: "Password Changed",
    user: "support@whms.io",
    ip: "192.168.1.101",
    time: "2024-06-01 08:30",
    severity: "info",
  },
  {
    id: 4,
    event: "2FA Disabled",
    user: "billing@whms.io",
    ip: "192.168.1.102",
    time: "2024-05-31 16:00",
    severity: "warning",
  },
  { id: 5, event: "IP Blocked", user: "System", ip: "103.25.48.91", time: "2024-05-31 14:20", severity: "critical" },
]

export const serverMetrics = [
  { time: "00:00", cpu: 45, memory: 62, requests: 1200 },
  { time: "04:00", cpu: 32, memory: 58, requests: 800 },
  { time: "08:00", cpu: 68, memory: 71, requests: 2400 },
  { time: "12:00", cpu: 82, memory: 78, requests: 3800 },
  { time: "16:00", cpu: 75, memory: 74, requests: 3200 },
  { time: "20:00", cpu: 58, memory: 68, requests: 2100 },
  { time: "Now", cpu: 52, memory: 65, requests: 1800 },
]
